### ISSUE TITLE
F is an undefined name

### ISSUE THREAD

**Issue by cclauss** [ikostrikov/pytorch-a2c-ppo-acktr#10]
https://github.com/ikostrikov/pytorch-a2c-ppo-acktr/blob/master/kfac.py#L15

**Comment by ikostrikov** [comment]
Thanks for reporting the problem! Fixed in https://github.com/ikostrikov/pytorch-a2c-ppo-acktr/commit/4a6969bb3ecd621f06160c62d0949e6231b695f4
