### ISSUE TITLE
NoneType' object has no attribute 'data'

### ISSUE THREAD

**Issue by nanxintin** [ikostrikov/pytorch-a2c-ppo-acktr#101]
Hi, when I loaded a pre-trained ACKTR model and continued to train the agent based on the model, an error happened:   "AttributeError: 'NoneType' object has no attribute 'data'"
This happened in kfac.py line 79.

class SplitBias(nn.Module):
    def __init__(self, module):
        super(SplitBias, self).__init__()
        self.module = module
        self.add_bias = AddBias(module.bias.data)
        self.module.bias = None

Could you give me some advice to fix this error? Thanks.

**Comment by timmeinhardt** [comment]
In #81 we fixed an issue with continuing training of ACKTR models and how the `SplitBias` is added. Maybe your pretrained model was trainer prior to that change. You could try to load the model with `load_state_dict` to circumvent that issue.
