### ISSUE TITLE
Implementing Recurrent policy for Multi-Layer Perceptron (MLPBase)

### ISSUE THREAD

**Issue by parthjaggi** [ikostrikov/pytorch-a2c-ppo-acktr#108]
I wanted to implement recurrent policy for MLPBase class.

Relatively new to PyTorch, so some pointers on what direction to take would be helpful. 
Would it be similar to 'gru' implementation in CNNBase.

**Comment by timmeinhardt** [comment]
The PR #93 already implements a recurrent policy for the MLP base class.

**Comment by timmeinhardt** [comment]
1. I tested the recurrent MLP code only on my local private environment. You could try one of the standard environments (see `README.md`) that work with a regular MLP policy.
2. Giving you detailed help regarding your own environment is probably quite difficult. But with respect to this issue: Did it work for your environment with an MLP without the recurrent option?

**Comment by ikostrikov** [comment]
We need to add memory reacher (provide target only for the first tilmestep), that's the easiest way to test it.

**Comment by ikostrikov** [comment]
The PR has been merged.

**Comment by ikostrikov** [comment]
I've added a wrapper to test recurrent policy:

https://github.com/ikostrikov/pytorch-a2c-ppo-acktr/commit/2ba808034dc0ff661f60d51da77e649d718c603c

Recurrent policy seems to work with Reacher (masked with this wrapper).
