### ISSUE TITLE
How do ppo & acktr compare in terms of wall-clock time?

### ISSUE THREAD

**Issue by ethancaballero** [ikostrikov/pytorch-a2c-ppo-acktr#11]
ACKTR paper says that ACKTR paper processes ~25% less steps per minute compared to A2C.
What percent less steps per minute does PPO process compared to A2C?

**Comment by ikostrikov** [comment]
On my machine I can barely notice any difference. PPO is slower, it depends on the epoch parameter.

**Comment by ethancaballero** [comment]
PPO is slower than ACKTR (or just slower than A2C)?

**Comment by ikostrikov** [comment]
PPO performs multiple updates for the same data sample. It's slower than ACKTR and A2C. But my experience that running environments is the main bottleneck anyway.
