### ISSUE TITLE
Potential bug in storage.py > compute_returns?

### ISSUE THREAD

**Issue by sg2** [ikostrikov/pytorch-a2c-ppo-acktr#110]
On the first line, we see that ```self.value_preds[step]``` is subtracted, but on the third line it is added back in. So it's actually not doing anything?
```
delta = self.rewards[step] + gamma * self.value_preds[step + 1] * self.masks[step + 1] - self.value_preds[step]
gae = delta + gamma * tau * self.masks[step + 1] * gae
self.returns[step] = gae + self.value_preds[step]
```

**Comment by timmeinhardt** [comment]
I think I agree and the last addition of `self.value_preds[step]` should not be there. But maybe we are missing something that @ikostrikov is aware of.

**Comment by ikostrikov** [comment]
It's correct. First we compute advantages using GAE and then recompute the targets using values + these advantages instead of true returns.

**Comment by titardrew** [comment]
@ikostrikov I'm afraid it's not. According to [paper](https://arxiv.org/pdf/1506.02438.pdf), GAE itself is an estimate of the advantage, hence it has to be used without extra addition of values. In other words, you estimate `A(s, a) = Q(s, a) - V(a)`, but then you add `V(a)` again, obtaining `Q(s, a)` which, I think, is not correct here. Also, the variable you called `gae`  is TD-residual (at least according to the paper, see par. 2) and is used as weight for gradients of log probabilities of actions taken yielded by the actor. Finally, at least it does not make sense to subtract values in delta assignment just to add it back in returns assignment.

**Comment by ikostrikov** [comment]
@titardrew could you elaborate?

I opened page 2 and looking at equation 6. It looks like ```delta``` in this code. ```gae``` is computed according to equation 16 (page 5). If the values were not substracted it would compute q-lambda instead of GAE. 

Do I miss something?

**Comment by titardrew** [comment]
> If the values were not substracted it would compute q-lambda instead of GAE.
@ikostrikov , it's correct and you do subtract values in code. But then you add them back 
```self.returns[step] = gae + self.value_preds[step]```
So as a result they are not subtracted.

**Comment by ikostrikov** [comment]
They are kept subtracted for further recursive computations. If the subtraction was removed, the result wouldn’t be the same due to the recursion.

**Comment by titardrew** [comment]
Sure, my point is that you should **remove the addition**:
```python
delta = self.rewards[step] + gamma * self.value_preds[step + 1] * self.masks[step + 1] - self.value_preds[step]
gae = delta + gamma * tau * self.masks[step + 1] * gae
self.returns[step] = gae  # + self.value_preds[step]
```
When you add values back you obtain Q(s, a) estimate instead of the whole advantage, so I think you should not do this.

**Comment by ikostrikov** [comment]
We still need to store Q values to compute V:
https://github.com/ikostrikov/pytorch-a2c-ppo-acktr/blob/57c3d84f013af6c6ba52699a40b687f54b21ed18/a2c_ppo_acktr/algo/ppo.py#L74

Advantages computed from returns when necessary:
https://github.com/ikostrikov/pytorch-a2c-ppo-acktr/blob/57c3d84f013af6c6ba52699a40b687f54b21ed18/a2c_ppo_acktr/algo/ppo.py#L35

Thus, keeping Q values is necessary. Keeping advantages instead is similar but it would require to restore Q values to compute V so it doesn't change much.

**Comment by titardrew** [comment]
Oh, okay. So you subtract them later. Thanks for making it clear.
