### ISSUE TITLE
[QUESTION] How does Visdom handle rewards from multiple environments?

### ISSUE THREAD

**Issue by KeirSimmons** [ikostrikov/pytorch-a2c-ppo-acktr#111]
If my understanding of the setup is correct, we instantiate a new environment for each process. I.e. if we use 8 processes, we have 8 environments. Does Visdom plot the rewards from a single process, or does it average them, or does it do something even more 'clever'? I've done some searching but couldn't find a good resource on what the best approach would be.

For more details, I am logging a lot more than just reward. In my environment the reward function is incredibly complex (a function of multiple different interacting penalties) - so I need to log the penalties all individually. This is fine - I pass through these values via the `info` return of the `step` method. But now I have 8 lists of penalties (one for each process) and I want to make sure that I am processing these in the same manner as visdom does for the reward plot.

I have read through the documentation for visdom and looked through the code here, but couldn't seem to find an answer. 

Thanks.

**Comment by ikostrikov** [comment]
Vizdom averages between environments and smoothes them.
