### ISSUE TITLE
Bugfix for python 3.5 

### ISSUE THREAD

**Issue by ranahanocka** [ikostrikov/pytorch-a2c-ppo-acktr#112]
Hi,

Currently, the scripts do not work in Python 3.5. specifically, at least lines 74-76 in storage.py are not supported. Can you make backwards compatible? Alternatively, I can also fix it and make a PR.

**Comment by ikostrikov** [comment]
Hi!

I will accept a PR.

**Comment by ranahanocka** [comment]
I submitted a PR [#113](https://github.com/ikostrikov/pytorch-a2c-ppo-acktr/pull/113).

@timmeinhardt It's nice to have backwards compatible code, makes it easier to attract more users. In this case, it's only a simple print statement, so I think it's a reasonable compromise :). Anyway, I am using lots of different python versions on various machines, and one of them happens to be 3.5

**Comment by ikostrikov** [comment]
@timmeinhardt I agree. I'm against supporting python 2.x. But 3.5 still seems reasonable, in some institutions it might take time to update software (something that I also experienced myself).

I accepted the PR.
