### ISSUE TITLE
observations in evaluation not transferred to GPU

### ISSUE THREAD

**Issue by rwightman** [ikostrikov/pytorch-a2c-ppo-acktr#117]
In the new evaluation addition, the observations are not transferred to the GPU when you're not using the VecPyTorchFrameStack wrapper.

Either the VecPyTorch should also be updated to take the device and transfer the obs on reset/step, or line 180 in main should have an `obs=obs.to(device)` inserted

**Comment by ikostrikov** [comment]
Yes, good catch!

I prefer to have everything PyTorch related in the wrapper.

Let me know if you have time to submit a PR.
