### ISSUE TITLE
Evaluation environments aren't being closed, processes accumulate

### ISSUE THREAD

**Issue by rwightman** [ikostrikov/pytorch-a2c-ppo-acktr#119]

**Comment by ikostrikov** [comment]
That's surprising. I expected it to be handled properly in the baselines VecEnv code.

For the moment, I would suggest a simple hack. I would get a list of envs and close them manually. It should be relatively easy to unwrap them.

I have an example here:
https://github.com/ikostrikov/pytorch-a2c-ppo-acktr/blob/master/enjoy.py#L31

I will be able to work on it on Monday (working on a deadline right now).

**Comment by ikostrikov** [comment]
Oh.
Sorry, didn't notice PR :)
