### ISSUE TITLE
ImportError: cannot import name 'BatchSampler'

### ISSUE THREAD

**Issue by marianophielipp** [ikostrikov/pytorch-a2c-ppo-acktr#12]
python main.py --env-name "PongNoFrameskip-v4"
Traceback (most recent call last):
  File "main.py", line 12, in <module>
    from torch.utils.data.sampler import BatchSampler, SubsetRandomSampler
ImportError: cannot import name 'BatchSampler'

**Comment by ikostrikov** [comment]
Thanks for reporting the problem! 

I think the issue is in the PyTorch version.

Try to update it from conda first. If it doesn't help, try to compile PyTorch from sources.

Let me know if it helps.

**Comment by marianophielipp** [comment]
Thanks! Yes, I need to check something with the pytorch installation even if was successful it seems that something is wrong.
