### ISSUE TITLE
'>' not supported between instances of 'float' and 'NoneType' 

### ISSUE THREAD

**Issue by Mehd6384** [ikostrikov/pytorch-a2c-ppo-acktr#122]
Hello, 

When running PPO various environments, I get the following error message: 
` '>' not supported between instances of 'float' and 'NoneType' `. I narrowed the error to the point where the Visdom server is initialized but I can't figure out why this happens. 

Also, I used the following command to launch the training: 
`python main.py --env-name "mreacher-v0" --algo ppo  --use-gae --lr 2.5e-4 --clip-param 0.1 --value-loss-coef 1 --num-processes 8 --num-steps 128 --num-mini-batch 4 --vis-interval 1 --log-interval 1`

Thanks !

**Comment by Mehd6384** [comment]
The environments is a custom one, but I get the same error when launching CartPole.

**Comment by ikostrikov** [comment]
Which version of python are you using?

**Comment by Mehd6384** [comment]
I'm on 3.6.5

**Comment by Mehd6384** [comment]
While the error occurs in a recurrent manner, the algorithm still functions. 

```
'>' not supported between instances of 'float' and 'NoneType'
Updates 6029, num timesteps 6174720, FPS 2272 
 Last 10 training episodes: mean/median reward 1.0/1.0, min/max reward 1.0/1.0

Updates 6030, num timesteps 6175744, FPS 2273 
 Last 10 training episodes: mean/median reward 1.0/1.0, min/max reward 1.0/1.0

Updates 6031, num timesteps 6176768, FPS 2273 
 Last 10 training episodes: mean/median reward 1.0/1.0, min/max reward 1.0/1.0

Updates 6032, num timesteps 6177792, FPS 2273 
 Last 10 training episodes: mean/median reward 1.0/1.0, min/max reward 1.0/1.0
```

But I thought best to find where lies the error.

**Comment by ikostrikov** [comment]
Do you use the most recent PyTorch/baselines/gym?

I don't get this error for cartpole

**Comment by Mehd6384** [comment]
I think I do. Could it be something with Visdom maybe  ?

**Comment by ikostrikov** [comment]
It doesn't look like a vizdom problem. Can you provide more information?

Is your env on github?

**Comment by ikostrikov** [comment]
Did you launch visdom in the background? python -m visdom.server

For me it works for version '0.1.8.5'.

**Comment by Mehd6384** [comment]
I did and I'm on the same version here which is strange. 

Overall, the algorithm worked and returned a functional policy, I was just surprised by this message

**Comment by ikostrikov** [comment]
The issue is already there
https://github.com/facebookresearch/visdom/issues/467
