### ISSUE TITLE
Change `num_mini_batch` to `mini_batch_size`

### ISSUE THREAD

**Issue by pemami4911** [ikostrikov/pytorch-a2c-ppo-acktr#123]
https://github.com/ikostrikov/pytorch-a2c-ppo-acktr/blob/2ba808034dc0ff661f60d51da77e649d718c603c/storage.py#L78

The check should be `NT >= M` where `M = NT // num_mini_batch`, not `NT >= num_mini_batch`. This applies to the recurrent generator as well. The strings in the `assert` statements should be updated too.

**Comment by pemami4911** [comment]
In https://github.com/ikostrikov/pytorch-a2c-ppo-acktr/blob/2ba808034dc0ff661f60d51da77e649d718c603c/storage.py#L99  it looks like `num_envs_per_batch = num_processes // num_mini_batch` is computed instead of `num_envs_per_batch = num_processes * num_steps // num_mini_batch` because the length `num_steps` episode is not being split into `num_steps` samples in the recurrent update? So here, `num_envs_per_batch` is the equivalent of `mini_batch_size`?

**Comment by ikostrikov** [comment]
Closed by a mistake, reopening.
