### ISSUE TITLE
About the trainning results

### ISSUE THREAD

**Issue by Nara0731** [ikostrikov/pytorch-a2c-ppo-acktr#127]
I have tried the PPO for Hopper-v2 and the A2C for BreakoutNoFrameSkip-v4. However, when trainning about 1M steps, the mean reward is far less than your results. For the Hopper-v2, it still remains 6.2 at 0.1M steps; For BreakoutNoFrameSkip-v4, it still remains 50.4 at 2M steps.

So, I donot know if other settings should be mentioned?

Regards
9/14

**Comment by ikostrikov** [comment]
Do you use the hyper parameters from readme?

**Comment by ikostrikov** [comment]
With these hyper parameters I get fro Hopper:
Updates 48, num timesteps 100352, FPS 846
 Last 10 training episodes: mean/median reward 415.6/414.7, min/max reward 396.3/426.4

**Comment by ikostrikov** [comment]
50 after 2m steps is reported for breakout in readme. To get better results it requires more training.

**Comment by Nara0731** [comment]
Yes, I have checked the hyper paras from README. In MuJoCo and A2C，I only need modify：
--num-stack  4->1
--num-frames 10e6->1e6
--add-timestep False-> True
En，I use the PyCharm，so I think I just need to modify the default of the arguments.py
Then I run the main.py
Updates 750, num timesteps 60080 FPS 86 mean/median reward10.5/11.8 min/max reward 2.3/17.0

**Comment by ikostrikov** [comment]
Try to launch it from terminal.

**Comment by Nara0731** [comment]
Now I am trying to launch it from terminal. 
python3 main.py --env-name "Hopper-v2" --num-stack 1 --num-frames 1000000

results:
update 210, num timesteps 16880, FPS 91 mean/median reward 6.5/6.4 min/max 5.0/8.1
...
...
update 1300, num timesteps 104880, FPS 91 mean/median reward5.0/2.6 min/max 0.5/15.0

**Comment by ikostrikov** [comment]
Are you using the latest version of this repository, gym and baselines?

**Comment by Nara0731** [comment]
Gym should be updated, baselines are the lastest.

**Comment by Nara0731** [comment]
Yeah, I have tried the hyper paras 

python main.py --env-name "Hopper-v2" --algo ppo --use-gae --vis-interval 1  --log-interval 1 --num-steps 2048 --num-processes 1 --lr 3e-4 --entropy-coef 0 --value-loss-coef 1 --ppo-epoch 10 --num-mini-batch 32 --gamma 0.99 --tau 0.95 --num-frames 1000000

It is still no work.

**Comment by ikostrikov** [comment]
Try to install everything from a scratch in a new python environment.
