### ISSUE TITLE
fisher loss

### ISSUE THREAD

**Issue by mehdimashayekhi** [ikostrikov/pytorch-a2c-ppo-acktr#133]
thanks for sharing code, would you mind explaining about fisher loss for policy and value function, here https://github.com/ikostrikov/pytorch-a2c-ppo-acktr/blob/1d4d984ef745d388bb6e2760d460348d8d9efb25/algo/a2c_acktr.py#L55 and here https://github.com/ikostrikov/pytorch-a2c-ppo-acktr/blob/1d4d984ef745d388bb6e2760d460348d8d9efb25/algo/a2c_acktr.py#L61, where exactly in paper refer to this? just to make sure I understand : is this  (in section 3.1 paper)```p(a, v|s) = π(a|s)p(v|s)```, so ```log p(a, v|s) = log π(a|s)+log p(v|s)``` (not sure, because no log for value part in the Implementation). and why the ```sample_values ``` is calculated like that, I mean adding value function with some noise. Appreciate your response

**Comment by ikostrikov** [comment]
See sections 3.1 and 5.3 of the original paper.
