### ISSUE TITLE
Value Function Clipping for PPO

### ISSUE THREAD

**Issue by ankeshanand** [ikostrikov/pytorch-a2c-ppo-acktr#136]
The new PPO implementations in the OpenAI baselines repository also perform Value Function clipping (https://github.com/openai/baselines/blob/master/baselines/ppo2/ppo2.py). 
It would be cool to have this implemented!

**Comment by ikostrikov** [comment]
https://github.com/ikostrikov/pytorch-a2c-ppo-acktr/blob/master/algo/ppo.py#L67

It's already in the repo. But I've disabled it by default since I'm getting worse results with it.

**Comment by ankeshanand** [comment]
Oh, thanks! I should have pulled from the master again before raising the issue. 
Yeah, I imagine the value loss clipping would help only when the critic training is high variance. I actually have such a case rn, will report back the results! 

Related point: I see that the value loss is scaled by `0.5` by default right now, in addition to having the `value_coef`. Won't this be confusing?

**Comment by ikostrikov** [comment]
Yes, I probably should just put everything into value_coef.
