### ISSUE TITLE
Multi-processor performance

### ISSUE THREAD

**Issue by hammertoe** [ikostrikov/pytorch-a2c-ppo-acktr#138]
I am finding that trying to use multiple processors is slowing things down.

If I try, 

```python main.py --env-name "myenv-v0"  --num-processes 1 --num-steps 20000 --recurrent-policy```

On my iMac (4 core) I get around 1000 fps. If I try `--num-processes 4` then I get about 200 fps, and none of the cores are at full utilisation

I also tried the same on a Linux GCE instance with 32 cores and got similar results. When running with `--num-processes 32` each process is only using about 7% of its CPU.

Any ideas?

**Comment by ikostrikov** [comment]
Do you decrease the number of steps?

**Comment by hammertoe** [comment]
I'm a bit confused as to how the steps work in this case. My environment is returning data from a saved set of data. It takes about 20,000 steps to work through the entire data. At the moment, each reset of the environment takes you to step `randint(0,100)`. If I decrease the number of steps, will that mean I don't cover the entire data set? Or should I perhaps change my environment to return a random slice of, say, 2,000 steps from the total of 20,000?

**Comment by ikostrikov** [comment]
For a standard MDP setup it would mean that instead of computing a return using rewards for 20k steps, it will use rewards for 2k steps and bootstrap for 2001th step.

**Comment by hammertoe** [comment]
So it would not call env.reset() at the 2001th step?

**Comment by ikostrikov** [comment]
No, it will only bootstrap at 2001th step, compute the update and will "restart" from 2001th step. And only after 20k steps it will reset it.

**Comment by hammertoe** [comment]
Am I correct in thinking that if I get it working right the FPS when running with multiple processes should be higher than for a single process?

**Comment by ikostrikov** [comment]
Not necessary.

It should be higher when batch_size = num_processes * num_steps is constant.

If num_processes is increased but num_steps is the same. Then the batch size is 4 times larger and it can perform fewer updates per second.

**Comment by hammertoe** [comment]
OK, maybe I'm still missing something then:

```
(pytorch) matt@big-pytorch:~/pytorch/pytorch-a2c-ppo-acktr$ python main.py --env-name "myenv-v0" --algo acktr --num-processes 1 --num-steps 2000
Updates 10, num timesteps 22000, FPS 1216 
 Last 8 training episodes: mean/median reward 27.2/27.7, min/max reward 21.0/33.1

Updates 20, num timesteps 42000, FPS 1224 
 Last 10 training episodes: mean/median reward 27.7/27.7, min/max reward 22.2/33.1
```

The above takes approx 15 seconds between those two outputs (20,000 steps)

```
(pytorch) matt@big-pytorch:~/pytorch/pytorch-a2c-ppo-acktr$ python main.py --env-name "myenv-v0" --algo acktr --num-processes 2 --num-steps 1000
Updates 10, num timesteps 22000, FPS 253 
 Last 8 training episodes: mean/median reward 26.1/24.9, min/max reward 20.4/35.8

Updates 20, num timesteps 42000, FPS 247 
 Last 10 training episodes: mean/median reward 26.3/26.1, min/max reward 21.8/30.4
```

The above takes approx 75 seconds between those two outputs (20,000 steps)

What am I doing wrong? This is a 32 cpu GCE server, no GPU.
