### ISSUE TITLE
Misleading usage of acc_stats in kfac optimizer.

### ISSUE THREAD

**Issue by ferrine** [ikostrikov/pytorch-a2c-ppo-acktr#142]
It is not obvious, how to use this, a simple inline comment would be extremely helpful
https://github.com/ikostrikov/pytorch-a2c-ppo-acktr/blob/4d95ec364c7303566c6a52fb0a254640e931609d/algo/kfac.py#L162

**Comment by ikostrikov** [comment]
Fixed in https://github.com/ikostrikov/pytorch-a2c-ppo-acktr/commit/2edf667a2e2bb2fcfe8f102b0a58576a69dad4e5
