### ISSUE TITLE
code doesn't seem to support atari-ram

### ISSUE THREAD

**Issue by ranahanocka** [ikostrikov/pytorch-a2c-ppo-acktr#144]
Hi,
Currently, the code will not work on the atari-ram environment (at least I can verify "Pong-ramNoFrameskip-v4"). Currently, in envs.py 

`       
if is_atari:
     env = wrap_deepmind(env)
`

where in wrap_deepmind (atari_wrappers.py) uses a function called WarpFrame which will modify the observation shape, no matter what was originally defined in:

`env.observation_space`

Is this behavior intentional? It seems a bit odd that the observation space is not directly input from the env.observation_space itself.

**Comment by ikostrikov** [comment]
Hi,

yes. It will not work for atari-ram. Some chances need to be made.

**Comment by ranahanocka** [comment]
Thanks. I'll give it a shot :)

**Comment by ikostrikov** [comment]
Fixed in https://github.com/ikostrikov/pytorch-a2c-ppo-acktr/issues/144
