### ISSUE TITLE
RolloutStorage

### ISSUE THREAD

**Issue by jaelim** [ikostrikov/pytorch-a2c-ppo-acktr#149]
Hello, Thanks for sharing a great repository. 

So, I'm trying to apply to this repo in other problem aside from Atari game. I was going through your `main.py`, and I found this `RolloutStorage`. I'm trying to understand it, but struggling to understand without a proper documentation. Can someone graciously provide some sort of highlights explaining what it's for and how it gets used? Also, if you were to use it in different problems, what parts do you suggest to make necessary changes? Thanks!

**Comment by ikostrikov** [comment]
Is there anything specific that you want to ask regarding RolloutStorage? Basically just as it says it stores rollouts from a policy (and also computes returns and that's it).

**Comment by jaelim** [comment]
@ikostrikov Thanks for replying. So, for instance as you've mentioned, I'm sure I understood what it means by "it stores rollouts from a policy (... computes returns)". So, in this instance, I'm not able to register what exact is rollouts are and what gets returns? I have a limited experience with DQN, so I'm roughly guessing this might be somewhat relating to experience replay buffer?

Hopefully, there's some attached documentation to the codes as that might help a lot to visitors.

**Comment by ikostrikov** [comment]
I think it's worth reading the original papers that describe A2C/A3C and PPO.
