### ISSUE TITLE
Why Modify standard PyTorch distributions?

### ISSUE THREAD

**Issue by xiaoiker** [ikostrikov/pytorch-a2c-ppo-acktr#150]
RT, what is the problem if I use the standard  PyTorch distributions?

**Comment by timmeinhardt** [comment]
From my understanding, this is just an interface issue. In the `Policy.act` method different distributions are called with the same method calls but different distributions, i.e., different action types, require different preprocessing. And the mode method is something that is not implemented at all.
The code is basically using the standard PyTorch distributions but with a modified interface.

**Comment by ikostrikov** [comment]
Yes, the problem was that they use a different interface so I had to adapt it.
