### ISSUE TITLE
How to draw the score curve of PPO or A2C?

### ISSUE THREAD

**Issue by FrigEgg** [ikostrikov/pytorch-a2c-ppo-acktr#158]
Hello,

I don't know how to draw the score curve PPO or A2C which in the paper of PPO or A2C? How to deal with the situation when the game is not over but the sample pool is full? In this cause if we end the game, it means that we cannot calculate the score which agent needs to perform more than Horizon (T) interactions with the environment to get, such as Walker2d-v1. But if we don't end the game when the sample pool is full, the number of samples maybe larger than Horizon (T).

I don't know how to deal with this problem. How do you deal with this problem in the PPO or A2C experiment? I really care about this. Thanks for your help.

**Comment by FrigEgg** [comment]
I am very grateful for your reply.

I think you are right, this is a great way to evaluate. But this problem don't just occur during evaluating. During training if we end the game when the sample pool is full, we cannot get the samples which are needed for training after T steps. Such as breakout, there are 256 minibatch each iter in Atari game which are introduced in PPO paper.

I have another question about "saving checkpoints every N steps and just use them to run evaluation". You see both of A2C and PPO use stochastic policy, so we should run N time in order to evaluation accurately. But we should calculate the mean of them, or max. If this is a supervised learning task, it would be mean. However, the performance of model is evaluated by the best score we get for reinforce learning. I don't know how which way was used in paper.

**Comment by ikostrikov** [comment]
It depends on a task. Since some games start from a random initial state, taking max might provide highly biased results. So taking a mean of top5 from 25 runs seems to be fair.

**Comment by FrigEgg** [comment]
I think that I understand it. Thanks you for your help!

**Comment by deepmeng** [comment]
How you draw the picture like this. @ikostrikov @AceChuse 
![image](https://user-images.githubusercontent.com/8176780/68994016-dd6af380-08b8-11ea-86db-c1dd0f2c01d0.png)
