### ISSUE TITLE
Atari games not learning?

### ISSUE THREAD

**Issue by nadavbh12** [ikostrikov/pytorch-a2c-ppo-acktr#16]
Tried training on different Atari games. It seems that using default parameters, neither Breakout nor Boxing were able to learn. Tried both acktor and a2c and waited for 10M steps
Though Pong managed to learn no problem.
Are you still able able to reproduce the results in the graphs in the readme?

**Comment by ikostrikov** [comment]
Do you check scores printed in logs or the ones in Visdom/Monitor?

There should be warning about clipped rewards for Atari. Logging prints clipped rewards only.

For Pong the scores are within [-1,1] so it’s not affected by clipping.

**Comment by nadavbh12** [comment]
Visdom:
![screenshot from 2017-11-01 16-55-16](https://user-images.githubusercontent.com/14809804/32280731-7dee4224-bf25-11e7-9f72-61eb9c46153a.png)

Inspecting the actual performance while training (using enjoy.py), I can see that the agent rarely outputs any action other than NOOP. Especially at the beginning of training I'm used to see frantic action selection.

**Comment by ikostrikov** [comment]
Ok. I'm checking everything now. I will provide an update within several hours.

**Comment by nadavbh12** [comment]
Thanks!

**Comment by ikostrikov** [comment]
A quick question.

Do you use the most recent baselines code? The very last commit (that contains a bug where you need to remove a line from __init__.py)?

**Comment by nadavbh12** [comment]
Yes. I also reverted to an older version of Baselines and to your code before the change.
Bad learning persisted.

**Comment by ikostrikov** [comment]
For me it clearly started learning.

![unknown](https://user-images.githubusercontent.com/1212494/32282367-bb247628-bef7-11e7-99cc-8e91df9b9fef.jpeg)

Try to use the most recent baselines code and just remove this line:
https://github.com/openai/baselines/blob/master/baselines/bench/__init__.py#L3

**Comment by nadavbh12** [comment]
That's strange. I've done as you've said but don't get your results.
Clearly the problem is on my side. I'll check it out, thanks and sorry for the false alarm.

**Comment by ikostrikov** [comment]
No worries. I'm glad to help anyway.

Try to have a clean conda env and install everything from a scratch.

I think that the problem happens because of the recent changes to the preprocessing code in the baselines.

**Comment by nadavbh12** [comment]
Tried again and it learnt. Must have been the wrong baseline commit.
