### ISSUE TITLE
How to load and retrain models on new data?

### ISSUE THREAD

**Issue by SerialIterator** [ikostrikov/pytorch-a2c-ppo-acktr#161]
I have a custom gym environment that I'm getting fairly good results on so far but I'd like to imitate what openai did and randomize the training levels to help with generalization. I figured the easiest way would be to train on one level, save the model, reload and train on a different level (many times) but I don't see any existing code to do that easily. I have used the `enjoy.py` file to test a model but seems like it would take quite some tweaking to use for retraining. If there's a straightforward way of doing it that I'm missing I'd greatly appreciate being pointed in the right direction. Thanks

**Comment by Akella17** [comment]
Hey, I would like to know why is getattr(get_vec_normalize(envs), 'ob_rms', None) saved along with actor-critc network (*line: 154-155, main.py*)? Won't saving the actor_critic network directly be enough to load the model?

**Comment by ikostrikov** [comment]
@Akella17 it's important to know normalization statistics for the inputs. Otherwise, the network will receive unnormalizes inputs after loading.
