### ISSUE TITLE
env.reset() for A2C and ACKTR

### ISSUE THREAD

**Issue by rasoolfa** [ikostrikov/pytorch-a2c-ppo-acktr#162]
Hi
Is there any reason that env.reset() [during training for A2C] was not called at the end of each rollout()? It only called one time https://github.com/ikostrikov/pytorch-a2c-ppo-acktr/blob/master/main.py#L90 .
For A3C, env.reset() is called at the end of every episode. 

Thanks for your help.

**Comment by ikostrikov** [comment]
It's called in the wrapper:
https://github.com/openai/baselines/blob/master/baselines/common/vec_env/subproc_vec_env.py#L13

**Comment by rasoolfa** [comment]
Thanks for your help.
