### ISSUE TITLE
Bug in TransposeImage?

### ISSUE THREAD

**Issue by Toraudonn** [ikostrikov/pytorch-a2c-ppo-acktr#163]
I was using a custom environment for OpenAI gym that has an `observation_space` of `Box(Height, Width, Channels)`, but the output for `TransposeImage` wrapper seems to be `Box(Channels, Width, Height)` instead of `Box(Channels, Height, Width)`.
It's a minor issue since most if not all gym environments have a square observation image.

Correct me if I'm wrong, but in this [line](https://github.com/ikostrikov/pytorch-a2c-ppo-acktr/blob/bc3a68fd2127754f81a1cf3f93ffc81b08667ce3/a2c_ppo_acktr/envs.py#L132), it should be:
```
class TransposeImage(gym.ObservationWrapper):
    ...
    def observation(self, observation):
        return observation.transpose(2, 1, 0)   # instead of .transpose(2, 0, 1)
```

**Comment by ikostrikov** [comment]
Yes, there is definitely a bug in this wrapper. Since the other line is inconsistent:
https://github.com/ikostrikov/pytorch-a2c-ppo-acktr/blob/bc3a68fd2127754f81a1cf3f93ffc81b08667ce3/a2c_ppo_acktr/envs.py#L128

I will take a closer look this evening.

**Comment by Toraudonn** [comment]
Hey, thanks for the quick response! Great job btw.

**Comment by ikostrikov** [comment]
The wrapper is confusingly named right now. A better name would be HeightWidthChannelToChannelHeightWidth.

Also in 
https://github.com/ikostrikov/pytorch-a2c-ppo-acktr/blob/bc3a68fd2127754f81a1cf3f93ffc81b08667ce3/a2c_ppo_acktr/envs.py#L128
```python
            [obs_shape[2], obs_shape[1], obs_shape[0]],
```

Should be
```python
            [obs_shape[2], obs_shape[0], obs_shape[1]],
```

You can create a pull request, for me it would take a couple of days to fix it myself.

**Comment by timmeinhardt** [comment]
Or you could call it `TransposeObs` and implement that it provides any kind of tranposing. And then specify the necessary transpose operation in `envs.py`. Like this the `TransposeObs` class might be of value for others who need other transposings and the naming is cleaner.

**Comment by ikostrikov** [comment]
@timmeinhardt I agree.

It should be implemented as a general transpose wrapper and we should have "hwc->chw" comment when we use transpose for pytorch.

**Comment by Toraudonn** [comment]
@ikostrikov, @timmeinhardt 
Thanks for your time!

I haven't had much time, but I fixed the bug and added a base class called `TransposeObs` in [this](https://github.com/ikostrikov/pytorch-a2c-ppo-acktr/pull/164#issue-250992603) pull request.
