### ISSUE TITLE
All the monitor files are not being displayed

### ISSUE THREAD

**Issue by Akella17** [ikostrikov/pytorch-a2c-ppo-acktr#171]
This issue arises because each process runs its own version of ```main.py```, i.e. the deletion of files (lines: 40-54, *main.py*) actually takes place ```num_processes``` times. Due to this parallelism, some processes have already created their ```monitor.csv``` file before the deletion code of other processes. This is causing the deletion of freshly created *monitor.csv* files.

**The reason for latency might be fewer cores (*number of cores = 4*) in my CPU**

Is there a workaround for making the deletion code in *main.py* (lines: 40-54) run only once?

**Comment by ikostrikov** [comment]
You need to store log files for different experiments in different folder (set --log-dir flag). For example as in 
https://github.com/ikostrikov/pytorch-a2c-ppo-acktr/blob/master/run_all.yaml

The reason why file are removed is that otherwise they might be polluted.

**Comment by Akella17** [comment]
Could you clarify what do you mean by "different experiments"? Are you referring to each process of *main.py* as a different experiment? It is confusing because you have made several changes to the code within 24hrs.

I am using on an older version of this repository (```num_step = 5``` and ```num_processes = 16```). In the older version, as we are using multiprocessing, the code in *main.py* is run 17 times (1 + num_processes). While the monitor.csv files are created by each of the child_processes (16 in total), each of these child_processes also tries to delete any existing files in the ```log-dir``` directory. My guess is that this won't be an issue if the CPU has more than 16 cores. However, as my CPU has only 4 cores, the 16 processes run in 4 batches of 4 and as a result I end up with 4 monitor.csv files each time I run the code.

I understand the reason why we want to delete previous monitor files before re-running the code.

**Comment by ikostrikov** [comment]
Child processes themselves do not delete monitor.csv files. They can only override them. Also each child process writes to it's own monitor.csv file.

By an experiment I mean running main.py

**Comment by Akella17** [comment]
All I am trying to say is that if you put a **print** statement in line: 39 *main.py*, it will be printed 17 times (*i.e.*, 1 + num_processes). Which means the code between lines: 41-54 also gets executed 17 times. For each child_process ```make_vec_envs``` (line: 61, *main.py*) creates a ```*.monitor.csv``` file in ```log_dir``` directory.

In simple words, each child_process after creation first tries to delete all the ```*.monitor.csv``` files in ```log_dir``` directory (line: 45, *main.py*) and then attempts to freshly create the respective ```(*(env_rank)*).monitor.csv``` file (line:61, *main.py*).

I guess you are trying to say that the child_processes don't have access to code written outside *main()* function. However, that's not the case in my local system.

**Comment by Akella17** [comment]
Hey, I went through the latest changes in the repository and the updates in the ```envs.py``` file has resolved the above-stated issue. Thanks :+1:
