### ISSUE TITLE
use beta distribution instead of gaussian when you add continuous actions

### ISSUE THREAD

**Issue by ethancaballero** [ikostrikov/pytorch-a2c-ppo-acktr#2]
Beta distribution seems to always work better than Gaussian on high dimensional continuous control tasks:

"Improving Stochastic Policy Gradients in Continuous Control with Deep Reinforcement Learning using the Beta Distribution"
http://proceedings.mlr.press/v70/chou17a/chou17a.pdf

**Comment by ikostrikov** [comment]
Thanks! I will try to implement it sometime later.
