### ISSUE TITLE
Continuous action space: range not taken into account

### ISSUE THREAD

**Issue by maximecb** [ikostrikov/pytorch-a2c-ppo-acktr#20]
Hello there!

I'm trying to train a CNN to control a robot with a differential drive. My gym environment has this action space:

```python
        self.action_space = spaces.Box(
            low=-1,
            high=1,
            shape=(2,)
        )
```

That is, I need the CNN to output two motor velocities in the range [-1, 1]. Unfortunately, at the moment, the low and high range of my action space isn't taken into account. I get outputs as high as 540, which makes the robot spin out of control.

This seems like it should be an easy problem to fix, but I'm still very new to PyTorch. Could you make the change, or advise me as to how to fix this?

**Comment by ikostrikov** [comment]
One solution is just to process actions in such a way that they are in [-1, 1], for example to add an action wrapper that uses tanh to remap them. But it's a little bit surprising that the output is so large (because the network is initialized to produce outputs roughly in the range of [-1, 1]). 

Do you normalize the inputs?

**Comment by maximecb** [comment]
What do you mean by normalize the inputs?

Regarding using tanh, do you think it would be a good idea to add code to always pass the outputs through tanh, and then remap that to the range of the action space?

**Comment by ikostrikov** [comment]
So they have zero mean and unit variance (also then you need to remove / 255 from the model).

Yes, but just as an action wrapper for gym.

**Comment by maximecb** [comment]
My images are in [0, 255], and not normalized.

The `CNNPolicy` takes the gym `action_space` as an input, so it should probably have the action scaling code.

**Comment by ikostrikov** [comment]
Ok. Then I will add it, it might help.

Yes, this is a good idea. I will try to add it this week.

**Comment by maximecb** [comment]
Thanks for being so responsive. Your code is the best PyTorch implementation of A2C/ACKTR I found. :)

**Comment by ikostrikov** [comment]
Thanks! I'm glad that this code can be useful.

At the moment, you can use this wrapper (I want to keep my code as consistent as possible with OpenAI implementations, but I'm going to add it to a new branch at some point). 

```
class ScaleActions(gym.ActionWrapper):
    def __init__(self, env=None):
        super(ScaleActions, self).__init__(env)

    def _step(self, action):
        action = (np.tanh(action) + 1) / 2 * (self.action_space.high - self.action_space.low) + self.action_space.low
        return self.env.step(action)
```

**Comment by maximecb** [comment]
> At the moment, you can use this wrapper

Thanks. I will give it a try. I do think you should scale the actions in the main branch though. If the actions aren't within the action space bounds, it's obviously a bug, even if OpenAI is doing it. TBH, I don't like their code that much. I find it's only geared to work with a few environments they tested, everything else requires modifications to the environment and to their code.

One small update: the huge action values are only a problem with your A2C implementation. This problem does not happen with ACKTR. The huge action values correspond with huge policy loss values (in the 10^9+ range).

**Comment by ikostrikov** [comment]
By the way, did you try to use PPO?

After playing with all algorithms I found PPO to be the most robust and reliable one.

**Comment by maximecb** [comment]
I didn't try PPO because of this requirement:

```
assert args.num_processes * args.num_steps % args.batch_size == 0
```

I can only run one process at the moment, my gym environment connects to a ROS/gazebo robot simulator.

**Comment by ikostrikov** [comment]
Oh. Actually, this requirement isn't really necessary. You can just remove this line and also change

```python
sampler = BatchSampler(SubsetRandomSampler(range(args.num_processes * args.num_steps)), args.batch_size * args.num_processes, drop_last=False)
```

```python
sampler = BatchSampler(SubsetRandomSampler(range(args.num_processes * args.num_steps)), args.batch_size * args.num_processes, drop_last=True)
```

**Comment by maximecb** [comment]
Hi again. There's an issue with wrapping the action outputs in a tanh I think. The actions quickly saturate at [1, 1]. At this point, I think the algorithm stays stuck there, unable to learn anymore. It would probably work better with a function that has less quick saturation?

Will try PPO now (without the wrapper)...

**Comment by ikostrikov** [comment]
I think it probably saturates so quickly because advantages are not normalized (so it makes a huge step). In PPO advantages are normalized so it should work better.

**Comment by maximecb** [comment]
Having an issue with PPO:

```
raceback (most recent call last):
  File "main.py", line 250, in <module>
    main()
  File "main.py", line 243, in main
    final_rewards.max(), -dist_entropy.data[0],
UnboundLocalError: local variable 'dist_entropy' referenced before assignment
```

**Comment by ikostrikov** [comment]
It means that an iteration of PPO didn't happen.

**Comment by maximecb** [comment]
That's what I thought. Due to there just being one process?

**Comment by ikostrikov** [comment]
Probably, because batch size was larger than the number of samples.

Try to keep drop_last = False.

**Comment by maximecb** [comment]
PPO does run with `drop_last = False`. The policy loss values seem normal. Action values don't seem to immediately saturate.
