### ISSUE TITLE
Setting random seed

### ISSUE THREAD

**Issue by bkj** [ikostrikov/pytorch-a2c-ppo-acktr#22]
Hi --

I'm trying to set this up so that it gets the _exact_ same results every time (eg, for regression tests).  Even when I set the seeds, I get (slightly) different results on each run.  Any ideas what might be going on there?

Thanks

**Comment by ikostrikov** [comment]
Hi!

cudnn convolutions are not deterministic. This is one of possible sources of stochasticity. Let me know if it's still non deterministic with other implementations of convolutions.

**Comment by bkj** [comment]
Ah good point -- let me test that and get back to you.

**Comment by bkj** [comment]
Doesn't look like that's the source of the nondeterminism.  If I build the `pytorch` from github and set the flag:

```
torch.backends.cudnn.deterministic = True
```

I still see the nondeterminism.  Same goes for if I set 

```
torch.backends.cudnn.enabled = False
```

If I run w/ `--no-cuda` option, then the results appear to be deterministic.

**Comment by ikostrikov** [comment]
Actually, this is interesting even without the context of RL.

Let's not close it yet, probably it makes sense to open an issue in the pytorch repo.

**Comment by bkj** [comment]
Yeah it's a little funny -- I don't totally believe I haven't made a mistake.  When I get a chance I'll put together something self-contained and open a `pytorch` issue if it persists.

**Comment by dannysdeng** [comment]
@bkj Hi, is it possible that in your testing code you haven't set "deterministic=True"? (as in model.py):  

> def.act(self, inputs, states, masks, **deterministic=False**):

**Comment by bkj** [comment]
(For posterity -- this bug was happening before pytorch added the `torch.backends.cudnn.deterministic` flag -- so it should be fixed now.)

**Comment by ikostrikov** [comment]
Thanks! I will add a deterministic option to the code today.
