### ISSUE TITLE
Invalid Syntax in kfac.py ?

### ISSUE THREAD

**Issue by shinshiner** [ikostrikov/pytorch-a2c-ppo-acktr#23]
I've tried to run this code, but it encountered `SyntaxError: invalid syntax` in line 44 of `kfac.py`, namely `return a.t()@(a / batch_size)`. Both python2.7 and python3.4 have this problem. Are there any solutions?

**Comment by ikostrikov** [comment]
@ operator for matrix multiplications was introduced in python 3.5.

**Comment by shinshiner** [comment]
Oh, thank you. I think I need to get python3.5 :)
