### ISSUE TITLE
Entropy of normal distribution

### ISSUE THREAD

**Issue by isacarnekvist** [ikostrikov/pytorch-a2c-ppo-acktr#25]
Thanks for sharing your code!

I think you have an issue here though:
https://github.com/ikostrikov/pytorch-a2c-ppo-acktr/blob/bcb4b5f8cfa2ae5332e9fcac72526d24579afcd5/distributions.py#L82

The entropy should look like this:
https://en.wikipedia.org/wiki/Multivariate_normal_distribution#Entropy

Here you also does not seem to be able to learn the variance:
https://github.com/ikostrikov/pytorch-a2c-ppo-acktr/blob/bcb4b5f8cfa2ae5332e9fcac72526d24579afcd5/distributions.py#L56

If I'm mistaken please let me know!

**Comment by ikostrikov** [comment]
Log std is fine (it's just a hack for KFAC). I implemented it similarly to add_bias function from tensorflow.

Entropy clearly looks like a mistake. But, fortunately, for PPO entropy coefficient was set to 0 so it wasn't affected.

**Comment by ikostrikov** [comment]
Fixed in https://github.com/ikostrikov/pytorch-a2c-ppo-acktr/commit/2fc89f22963c6cb1499d8198581f0f80f9f63ca4
