### ISSUE TITLE
LazyFrames

### ISSUE THREAD

**Issue by jvmancuso** [ikostrikov/pytorch-a2c-ppo-acktr#27]
Is there any elegant way to incorporate the `LazyFrames` memory optimization trick from `baselines.common.atari_wrappers`?  `WrapPyTorch` seems to prevent us from using `frame_stack=True` in `wrap_deepmind`, and the naive hack of converting to a numpy array in the `_observation` method nullifies the memory optimization provided by `LazyFrames`.

**Comment by ikostrikov** [comment]
If I understand it correctly, LazyFrames are needed for environments with a very large buffer (for example DQN).

What is the specific use case you need them for?

**Comment by jvmancuso** [comment]
Yes, probably should've specified that.  I'm working on reproducing DQN with exact hyperparameters from the original paper for a project associated with the ICLR Reproducibility Challenge.  So I'm trying to store 1,000,000 frames.

**Comment by ikostrikov** [comment]
OpenAI used a wrap_dqn wrapper:
https://github.com/openai/baselines/blob/master/baselines/deepq/experiments/atari/train.py#L66

But it looks like it's deprecated.

I would suggest to concatenate frames manually, as currently done in my code.

**Comment by jvmancuso** [comment]
Well, I think manually concatenating frames and storing those concatenations in the replay buffer causes memory use to balloon, since you're storing up to four copies of the same frame while it's in the buffer.  I was just wondering if you had any insight into this.  I think I'll just have to manually transpose the arrays after each sample comes out of the replay buffer in order to keep using the `LazyFrames`.  Thanks though!
