### ISSUE TITLE
Python 2 Support

### ISSUE THREAD

**Issue by araffin** [ikostrikov/pytorch-a2c-ppo-acktr#28]
Hello,
I forked your repo and did minor edits in order to get it work with python 2:
https://github.com/araffin/pytorch_agents/tree/python2

There is an additional change required in OpenAI Baselines (https://github.com/openai/baselines/blob/master/baselines/common/dataset.py#L50):
The definition (line 50):
```python
def iterbatches(arrays, *, num_batches=None, batch_size=None, shuffle=True, include_final_partial_batch=True):
``` 
need to be replaced by:
```python
def iterbatches(arrays, num_batches=None, batch_size=None, shuffle=True, include_final_partial_batch=True):
```

Do you want me to do a pull request ?

**Comment by ikostrikov** [comment]
Hi! I will gladly accept python 2 support PL.

Why do we need to modify iterbatches?

**Comment by araffin** [comment]
`DummyVecEnv` (line 17 in main.py)  imports `baselines.common.dataset` and that file gives a `SyntaxError: invalid syntax` because it uses[ Python 3 keyword only argument](https://www.python.org/dev/peps/pep-3102/) in `iterbatches` function

Unfortunately, that is not compatible with Python 2

**Comment by ikostrikov** [comment]
Yes, if you can submit a pool request to their repo it will be great.

**Comment by araffin** [comment]
Well, I think the problem is that they don't plan to support python 2:
https://github.com/openai/baselines/issues/134
https://github.com/openai/baselines/blob/master/setup.py#L4

**Comment by ikostrikov** [comment]
Is there a workaround? I was going to add baselines as a submodule.

**Comment by araffin** [comment]
The workaround would be to fork baselines, but that is not really convenient.

**Comment by ikostrikov** [comment]
Not fixable at the moment since https://github.com/openai/baselines/issues/177
