### ISSUE TITLE
Compare with Uncertainty Bellman Equation 

### ISSUE THREAD

**Issue by AjayTalati** [ikostrikov/pytorch-a2c-ppo-acktr#3]
The new "Uncertainty Bellman Equation" seems to give SOTA results - would be interesting to add this to your great list of algorithms :+1: 

[Uncertainty Bellman Equation and Exploration](https://arxiv.org/pdf/1709.05380v1.pdf)

**Comment by ethancaballero** [comment]
Might as well add Distributional Value function too:
"A Distributional Perspective on Reinforcement Learning"
https://arxiv.org/abs/1707.06887

**Comment by ikostrikov** [comment]
Thanks! I will try to implement it sometime later.

**Comment by GoingMyWay** [comment]
@ikostrikov  Hi, is Uncertainty Bellman Equation (UBE) available now?
