### ISSUE TITLE
default load_dir in enjoy.py is incorrect

### ISSUE THREAD

**Issue by maximecb** [ikostrikov/pytorch-a2c-ppo-acktr#30]
Hi there, it's me again!

There is a minor issue in `enjoy.py`. You have: `save_path = os.path.join(args.save_dir, args.algo)` in `main.py`. However, the algorithm name isn't taken into account in `enjoy.py`. I would suggest adding an `--algo` argument to enjoy.py, to keep it similar to what main.py expects.

There is also another problem, seemingly, with the `.act()` function being called with two arguments missing. It's missing two variables. These are not actually used in the PyTorch code, as far as I can tell, but the `.act()` function expects them.

**Comment by ikostrikov** [comment]
I was intended to be this way since models rarely depend on algorithms.

**Comment by maximecb** [comment]
What about the second problem?

**Comment by ikostrikov** [comment]
Hm. I can you send the specific line? All call of .act that I can find take 3 variables.

**Comment by maximecb** [comment]
My code is probably out of date. My bad.
