### ISSUE TITLE
typo in arg

### ISSUE THREAD

**Issue by CarloLucibello** [ikostrikov/pytorch-a2c-ppo-acktr#35]
There is a typo in the description of the argument `--max-grad-norm`. 
```python
    parser.add_argument('--value-loss-coef', type=float, default=0.5,
                        help='value loss coefficient (default: 0.5)')
    parser.add_argument('--max-grad-norm', type=float, default=0.5,
                        help='value loss coefficient (default: 0.5)')
```
Also, is 0.5  an appropriate default value (it is suspiciously equal to the value-loss-coef one)?

Bye
C

**Comment by ikostrikov** [comment]
I took the hyper parameter from OpenAI baselines:
https://github.com/openai/baselines/blob/master/baselines/a2c/a2c.py#L22

Fixed in https://github.com/ikostrikov/pytorch-a2c-ppo-acktr/commit/8d7f42456f1a3b685ecab50d4ba1e7398ed55a26
