### ISSUE TITLE
Hyperparameter for mujoco environment

### ISSUE THREAD

**Issue by a7b23** [ikostrikov/pytorch-a2c-ppo-acktr#38]
Hi I was able to get the desired plot for Reacher -v1 using PPO but was unable to do it for the HalfCheetah-v1 env. Did you use the same set of hyperparameter values for all the Mujoco game environments for PPO algorithm?

**Comment by ikostrikov** [comment]
Hi,

plots are a little bit outdated (see the exact commit that added the plots to get the same results).

Also HalfCheetah has very large variance, so you need to run it multiple times to get similar plots.

How big is the difference for HalfCheetah?
