### ISSUE TITLE
Catch small bin_size parameters

### ISSUE THREAD

**Issue by timmeinhardt** [ikostrikov/pytorch-a2c-ppo-acktr#43]
This part of the visualization https://github.com/ikostrikov/pytorch-a2c-ppo-acktr/blob/163f0199a89339711ba09ce28420b554f6bf024d/visualize.py#L19 breaks if the bin_size is not at least 3. Maybe catch small bin sizes with an assert?

**Comment by ikostrikov** [comment]
Hi!

Sorry, I've just noticed the issue.

Yes, it looks like a bug but it should be caught by a try ... catch block.
