### ISSUE TITLE
Is there a way to track the episode length?

### ISSUE THREAD

**Issue by bearpaw** [ikostrikov/pytorch-a2c-ppo-acktr#47]
Hi Ilya,

I'm trying to solve the navigation task with your implementation of A2C. An example is here: https://github.com/zfw1226/icra2017-visual-navigation/blob/master/training_thread.py#L161

One evaluation metric is the episode length, i.e., the number of steps the agent takes from the start location to the target location. I was wondering if there is a way to track the episode length in your code? It is easy to track the episode length with A3C since training threads are independent of each other. Thank you very much!

**Comment by ikostrikov** [comment]
Hi!

Yes, it can be done the same way rewards are accumulated. Just use the mask to "reset" lengths of episodes:

https://github.com/ikostrikov/pytorch-a2c-ppo-acktr/blob/master/main.py#L131
