### ISSUE TITLE
Why are the value_loss and action_loss summed?

### ISSUE THREAD

**Issue by lintangsutawika** [ikostrikov/pytorch-a2c-ppo-acktr#48]
Why are the `value_loss` and `action_loss` summed together in line 185 of `main.py`, 
```
(value_loss * args.value_loss_coef + action_loss - dist_entropy * args.entropy_coef).backward()
```
when they were both derived separately in line 163 and 165 and when both networks are meant to be separate models? I don't quite understand. Thank you in advance!

**Comment by ikostrikov** [comment]
It's done for generality. PyTorch will treat them as separate models when actor and critic represented as separate networks.

**Comment by lintangsutawika** [comment]
I also noticed that you included ```dist_entropy```, why did you include the cross-entropy in the actor-critic model? Do you have any literature that includes the entropy term? Thanks for the help!
