### ISSUE TITLE
Adding Prioritized Experience Replay 

### ISSUE THREAD

**Issue by AjayTalati** [ikostrikov/pytorch-a2c-ppo-acktr#5]
Hi, I was wondering if a Prioritized Experience Replay buffer could be added to PPO?

They do something similar to that here - [Leveraging Demonstrations for Deep Reinforcement
Learning on Robotics Problems with Sparse Rewards](https://arxiv.org/abs/1707.08817), with DDPG. 

I'm guessing though PPO would be more stable? 

Perhaps OpenAI's prioritized [replay_buffer](https://github.com/openai/baselines/blob/master/baselines/deepq/replay_buffer.py), from the baselines repo could be used?

**Comment by ikostrikov** [comment]
For PPO, it will probably have a much smaller effect since the replay buffer is much smaller.
