### ISSUE TITLE
large negative rewards for Pong

### ISSUE THREAD

**Issue by ammirato** [ikostrikov/pytorch-a2c-ppo-acktr#55]
When running
`python main.py --env-name "PongNoFrameskip-v4"`

The system doesn't seem to learn, and I get large negative mean rewards. Here is an example print out:

`Updates 10030, num timesteps 802480, FPS 1828, mean/median reward -20.4/-20.0, min/max reward -21.0/-19.0, entropy 1.77331, value loss 0.02498, policy loss 0.03232`

![pong_visdom](https://user-images.githubusercontent.com/33880090/36754669-b349b304-1bd7-11e8-84e6-9dd2904a2d2a.jpg)

**Pytorch Version** 0.3.1
**Baselines** most recent commit (b71152eea0470ac2629c33e0fc66a54fe494949f)

I have tried running it multiple times and have gotten the same result.

**Comment by ammirato** [comment]
**Update:**  Training for Seaquest seems to work. 

![seaquest_visdom](https://user-images.githubusercontent.com/33880090/36755703-ffe37d64-1bda-11e8-8c29-a0953469fc48.jpg)

**Comment by ikostrikov** [comment]
Did you try to run multiple random seeds on pong?

Some seeds (rarely) just don't work.

**Comment by ammirato** [comment]
Yes, I've tried a few different seeds with no difference in performance.

**Comment by ikostrikov** [comment]
It seems to work for me. Did you update gym?

**Comment by ammirato** [comment]
I have gym-0.10.3.  

I'm closing as leanring works for Seaquest, I assume there is just something wrong with my installed Pong environment.

**Comment by codeislife99** [comment]
Pong works very well. Use a larger rollout (args.num_steps) like 128 or 200 if you are using PPO, it converges within 50 updates. A2C also works with num-steps set to 5 but takes a lot longer.
