### ISSUE TITLE
K-FAC

### ISSUE THREAD

**Issue by lukashermann** [ikostrikov/pytorch-a2c-ppo-acktr#57]
Is it possible to use your implementation of K-FAC as an optimizer for other RL algorithms (e.g. DDPG) or is it especially designed for ACKTR?

**Comment by ikostrikov** [comment]
Yes, it can be used. You just need to change the computations of Fisher to  https://github.com/ikostrikov/pytorch-a2c-ppo-acktr/blob/master/main.py#L167

In this case it's PG loss + regression loss, in case of DDPG it will be two regression losses.
