### ISSUE TITLE
Missing Documentation Plotting Script

### ISSUE THREAD

**Issue by araffin** [ikostrikov/pytorch-a2c-ppo-acktr#58]
Hello,
Although I understand the general idea of the plotting script (smooth the reward curve), I have some trouble to understand the different functions in detail.

First, what is the idea behind `fix_point(x, y, interval)` ?

Then, in the smoothing function:
```python
def smooth_reward_curve(x, y):
    # Halfwidth of our smoothing convolution
    halfwidth = min(31, int(np.ceil(len(x) / 30)))
    k = halfwidth
    xsmoo = x[k:-k]
    ysmoo = np.convolve(y, np.ones(2 * k + 1), mode='valid') / \
        np.convolve(np.ones_like(y), np.ones(2 * k + 1), mode='valid')
    downsample = max(int(np.floor(len(xsmoo) / 1e3)), 1)
    return xsmoo[::downsample], ysmoo[::downsample]
```

What does 30 and 31 correspond to in `halfwidth = min(31, int(np.ceil(len(x) / 30)))` ?

PS: the two links at the top of the script are dead link now...

**Comment by ikostrikov** [comment]
Hi, I took this code from @emansim . I think he can provide a better explanation.

**Comment by ikostrikov** [comment]
I'm going to get rid of the current plotting. So I'm closing the issue.
