### ISSUE TITLE
Custom Env log problems

### ISSUE THREAD

**Issue by heitorrapela** [ikostrikov/pytorch-a2c-ppo-acktr#59]
Hello guys, I'm having problems to log my custom env. It doesn´t write in the .csv. I tried to understand where the data is writing, but I didn`t found it.

The only data written is: 
#{"t_start": 1521155105.3171377, "env_id": "my_custom_env"}
r,l,t

Could someone help me with it?

**Comment by ikostrikov** [comment]
Could you provide more information regarding your environments?

**Comment by heitorrapela** [comment]
Yes sir, I'm using vrep env, made by my friend: https://github.com/R3NI3/pytorch-a2c-ppo-acktr/tree/devel_vrepEnv_Renie_v0 . We couldn't figure it out what happend, my thought that can be the baseline version...
