### ISSUE TITLE
Could you share the hyper-parameters of a2c with different discrete action space

### ISSUE THREAD

**Issue by BoyuanYan** [ikostrikov/pytorch-a2c-ppo-acktr#60]
I tried default settings with discrete action space Discrete(6), but it doesn't work when size of action space is 16, 26, and even 41. So, could you provide some tips or your hyper-parameters when training games with larger action space?
Thanks so much!!!

**Comment by ikostrikov** [comment]
I think these methods might not scale well to high dimensional spaces.
