### ISSUE TITLE
Missing `args.value_loss_coef`?

### ISSUE THREAD

**Issue by lcswillems** [ikostrikov/pytorch-a2c-ppo-acktr#67]
https://github.com/ikostrikov/pytorch-a2c-ppo-acktr/blob/17ea8333ecbfe6552470f50fab4f83e1444f43a6/main.py#L226

**Comment by ikostrikov** [comment]
Yes, you are right.

Let me check what coefficient they used in the original paper and I will add it to default parameters and this line.

**Comment by ikostrikov** [comment]
Fixed in https://github.com/ikostrikov/pytorch-a2c-ppo-acktr/commit/9614c08685ab74f5576fd4e4ed2f6954709868b8
