### ISSUE TITLE
Suggestion: Mujoco - add timestep to the observation

### ISSUE THREAD

**Issue by tesslerc** [ikostrikov/pytorch-a2c-ppo-acktr#68]
See for example here: https://github.com/pat-coady/trpo
A major issue in Mujoco domains is that the test terminates due to timeout after a fixed number of steps.
This causes the state to be non-markovian (states near the end of the timelimit and identical states at the begining, have a different value assigned).

**Comment by ikostrikov** [comment]
That's a good suggestion. Let me check if OpenAI already have a wrapper for that.

**Comment by ikostrikov** [comment]
By the way, in the repo you mentioned, do they do this only for an actor or for a critic as well

**Comment by tesslerc** [comment]
Both (as if the original observation had this data).
