### ISSUE TITLE
invalid syntax: main.py, line 60, pos 49  ??

### ISSUE THREAD

**Issue by cn3c3p** [ikostrikov/pytorch-a2c-ppo-acktr#7]
"invalid syntax: main.py, line 60, pos 49 in file /home/pytorch-a2c-ppo-acktr-new/main.py
obs_shape = (obs_shape[0] * args.num_stack, *obs_shape[1:])" , is it ok?

**Comment by ikostrikov** [comment]
What python version are you using?

**Comment by cn3c3p** [comment]
Python 2.7.12 ，torch.__version0.1.12_2

**Comment by ikostrikov** [comment]
Yeah, this is a problem with python 2. Try python 3. If it's critical to use python 2, I can fix the issue.
