### ISSUE TITLE
Deterministic Policy

### ISSUE THREAD

**Issue by timmeinhardt** [ikostrikov/pytorch-a2c-ppo-acktr#74]
Although the current implementation of the policy takes a `deterministic` argument it is never applied and all policy sample random actions even for testing.
https://github.com/ikostrikov/pytorch-a2c-ppo-acktr/blob/552eb86bbc3e338a898d4adcc506d63fdbabebe0/model.py#L39

**Comment by ikostrikov** [comment]
Yes, that's a bug. I will fix it now

**Comment by ikostrikov** [comment]
Fixed in https://github.com/ikostrikov/pytorch-a2c-ppo-acktr/commit/a0cf2cfdd42f6305fb26e26589a513570dcc3ddb

**Comment by timmeinhardt** [comment]
Thank you for fixing this. Maybe I should have made a PR but just as a small note I think 
`FixedCategorical.mode = lambda self: self.probs.argmax(dim=1, keepdim=True)` would be more readable and inline with the `sample` method.

**Comment by ikostrikov** [comment]
Oh. I didn't know that they have argmax :) Could you still make a PR?
