### ISSUE TITLE
if self.linear1 = nn.LSTMCell

### ISSUE THREAD

**Issue by cn3c3p** [ikostrikov/pytorch-a2c-ppo-acktr#8]
at model.py, if self.linear1 = nn.LSTMCell, how about the performance  will be result ?

**Comment by ikostrikov** [comment]
I didn't try to use LSTMs here, I expect to see the same performance with LSTMs on Atari.

**Comment by ethancaballero** [comment]
You will need to mask the LSTM states from previous episodes like in TF implementation:
https://github.com/openai/baselines/blob/3f676f7d1e16a0880cb7fed5850bc00efba413d6/baselines/a2c/utils.py#L76-L98
^ms is tensor of which states to mask.

Also, layernorm on LSTM might help.

**Comment by cn3c3p** [comment]
thanks a lot!
