### ISSUE TITLE
VecNormalize gamma parameter

### ISSUE THREAD

**Issue by timmeinhardt** [ikostrikov/pytorch-a2c-ppo-acktr#87]
I agree that it makes very much sense to apply the same gamma for the reward discounting as well as the decay of the running averages of the `VecNormalize`:
https://github.com/ikostrikov/pytorch-a2c-ppo-acktr/blob/34b46eac0abd61e7fb20ff78bb2066eecf5ea7d5/main.py#L66

However, if someone uses the code for an undiscounted (gamma = 1.0) reward accumulation (as it is sometimes the case for Monte-Carlo style updates) this becomes problematic. While it makes sense to summarise all undiscounted rewards over the course of one episode, the same is not true for the running mean which accumulates the rewards of all previous steps and episoded.

I suggest an appropriate warning if gamma=1.0 to save other people from debugging this problem

**Comment by ikostrikov** [comment]
Yes, a warning sounds reasonable.

**Comment by timmeinhardt** [comment]
Due to a change in the `VecNormalize` code ( https://github.com/openai/baselines/blob/4dc697e670aecc5b9ef540ef95c175258f5da59e/baselines/common/vec_env/vec_normalize.py#L29) this warning is not necessary anymore because the accumulated returns for normalisation are reset after an environment is done. So I think we can close this issue.
