### ISSUE TITLE
CartPole-v0 reward above 200. 

### ISSUE THREAD

**Issue by codeislife99** [ikostrikov/pytorch-a2c-ppo-acktr#88]
I understand that there is a Running Mean and Running Std Dev calculation and all that. But that doesn't tell me why the mean/median reward goes above 200, if the history of observations after done is regularly cleaned.

**Comment by timmeinhardt** [comment]
Not exactly sure what you are getting at but in addition to the running mean and standard deviation the raw episode returns of each environment are saved with the baselines `bench.Monitor` helper. The corresponding directory is the `--log-dir` command line argument.

**Comment by codeislife99** [comment]
When you run the main.py file the reward for CartPole-v0 shouldn't go above 200. By reward I mean the mean/median reward and min/max reward which is printed on the terminal. Although this might not be the real reward it still shouldn't go above 200 because observations are supposed to be cleaned after every 200 time steps.

**Comment by timmeinhardt** [comment]
Yes, the mean/median and min/max rewards are based on the `final_rewards` which are processed by the `VecNormalize` wrapper. The normalisation includes a division by the running standard deviation (variance) which can be quite small in the beginning and therefore results in large processed rewards. See also my question in the OpenAI baselins repository https://github.com/openai/baselines/issues/266 

If you want to observe the real raw rewards you should work with Visdom and the `visdom_plot ` function of this repository.

**Comment by codeislife99** [comment]
Ahh, I forgot about the division with standard deviation. Makes sense now, thanks!
