### ISSUE TITLE
shared weights

### ISSUE THREAD

**Issue by mkbera** [ikostrikov/pytorch-a2c-ppo-acktr#94]
In many implementations, I see that they have used shared weights for actor and critic. It is also recommended in the PPO paper. Why are the weights not shared in this implementation?

**Comment by alok** [comment]
PPO could be easily shared, though for something like TRPO, this is a huge pain. I've tried both shared and unshared for PPO and it doesn't make *that* much of a difference when I've done it.

**Comment by ikostrikov** [comment]
@mkbera They are shared for atari environments. But not for mujoco ones. 

Currently, the code for model definition is confusing. I will try to clean it up.
