### ISSUE TITLE
Question about PPO

### ISSUE THREAD

**Issue by sg2** [ikostrikov/pytorch-a2c-ppo-acktr#95]
I'm able to quickly get excellent performance when a2c is chosen as the algo in arguments.py. But when I change it to ppo, it doesn't seem to learn anything (with all other arguments being the default). Do I need to change anything else to get ppo to solve PongNoFrameskip-v4?

Thank you very much for making this code available.

**Comment by codeislife99** [comment]
You should increase the number of rollouts to 100 or more to get it working with Pong, increasing the number of environments also helps converge much faster. I have used this code to solve Pong in about 50-100 updates depending on the hyperparameters.

**Comment by ikostrikov** [comment]
@sg2 did you try the parameters specified in the readme file?

**Comment by sg2** [comment]
Thank you, @ikostrikov. I read the readme a while back, but I forgot that the ppo call was given there. Of course it's training great now that I'm using the correct call.

And thanks, @codeislife99. I will experiment with the hyperparameters.
