### ISSUE TITLE
Naive question: why there is no envs.reset() in main.py?

### ISSUE THREAD

**Issue by PengZhenghao** [ikostrikov/pytorch-a2c-ppo-acktr#99]
Hi, @ikostrikov thanks for your great and clear codes!

The question may sound stupid, but I am unable to find `envs.reset()` in `main.py` training loop. Isn't that necessary for user to reset the environment in each iteration of outer loop?

**Comment by PengZhenghao** [comment]
Oh I see!
In `baselines/common/vec_env/subproc_vec_env.py`
There is code:

```
def worker(remote, parent_remote, env_fn_wrapper):
    parent_remote.close()
    env = env_fn_wrapper.x()
    while True:
        cmd, data = remote.recv()
        if cmd == 'step':
            ob, reward, done, info = env.step(data)
            **if done:**
                **ob = env.reset()**
            remote.send((ob, reward, done, info))
        elif cmd == 'reset':
            ob = env.reset()
            remote.send(ob)
        elif cmd == 'render':
            remote.send(env.render(mode='rgb_array'))
        elif cmd == 'close':
            remote.close()
            break
        elif cmd == 'get_spaces':
            remote.send((env.observation_space, env.action_space))
        else:
            raise NotImplementedError
```

That is, the environment stay in the subprocess are kept running and reset itself if `done` signal is raised. Therefore in the loop of main process, there is no need to manually reset the environments.

Sorry for this stupid question...

**Comment by Robin-des-Bois** [comment]
I just asked myself the same question. At the moment I would like to run an adapted version of this code with `num_proccesses = 1` because my environment does not work yet with multiple workers. 

In this case, the environment gets only `reset` once (at line 100). 

I inserted these two lines between line 125 and line 126
```
if isinstance(envs, DummyVecEnv) and done[0]:
    envs.reset()
```

Is there a better way to fix this issue?
